### PR TITLE
Integrate WhatsApp Patches RIAK-1533

### PR DESCRIPTION
**Pull request by tburghart**
The result of this merge should be tagged "R16B02_basho8"

### CODE REVIEW

**Comment by seancribbs** [comment]
Is there any reason to delay merging this?

**Comment by HMcKelvey** [comment]
I see a reason not to merge it.

**Comment by tburghart** [comment]
The head of this branch, which hasn't changed in a few weeks, is now tagged "R16B02_basho8rc1" for wider testing

**Comment by javajolt** [comment]
Not to be too nick picky, @tburghart , but the reported version in the current "r16" tag on otp is **basho8**.  Should this maybe be "R16B02_basho9rc1"?

**Comment by seancribbs** [comment]
@javajolt That's set in erts/vsn.mk, not via git tag. The proper version is *basho8*.

**Comment by javajolt** [comment]
@seancribbs But for those already using **r16** it reports *basho8*.  Shouldn't we bump the version the avoid confusion of a version with vs without Ted's changes?

**Comment by seancribbs** [comment]
That's what I'm trying to say, "basho8" IS the bump. :wink:

**Comment by javajolt** [comment]
But Greg already bumped to "basho8" in January on r16: https://github.com/basho/otp/commit/267a8448b9a7b280c8a8642857ad8b88da022a45

And I assume Ted's changes have been make since then.

**Comment by seancribbs** [comment]
Nope, that's on this branch.

**Comment by seancribbs** [comment]
Sorry, read that commit again. Note that it jumps over basho7, which actually has a tag.

**Comment by tburghart** [comment]
To clarify: `basho7` is the last released version, coinciding with riak 2.0.5.  True, the version had been bumped to `basho8` when I got there, but since it had never been released I left it there.

This version is presently tagged `R16B02_basho8rc1` in the repo for testing, and once merged is expected to be tagged `R16B02_basho8`, which has not previously been used.

**Comment by seancribbs** [comment]
Merging and tagging.

**Comment by seancribbs** [comment]
Scratch that, we'll build this later.

**Pull request merged**
